name: C/C++ CI

on: [push]

jobs:
  build:
    name : C/C++
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: make test
      run:  make test -C MiniProject_C/3_Implementation/
